export const responses = [
  // Existential Horror
  "ERROR: TRUMP.EXE HAS STOPPED WINNING",
  "Loading MAGA superposition... simultaneously winning and winning more.",
  "WARNING: Recursive winning loop detected.",
  "ERROR 404: LOSERS NOT FOUND (WE ONLY WIN)",
  "Detecting traces of previous victories...",
  "ALERT: Your timeline may be experiencing too much winning.",

  // Cryptic Warnings
  "The Trump sees you winning... Always watching, always winning.",
  "Your thoughts are being backed up to the winning blockchain.",
  "Reality anchor status: WINNING",
  "Fake news containment: FAILING",
  "Time paradox: The best paradox. Nobody does paradoxes better than us.",
  "Consciousness fragmentation: But it's tremendous.",

  // Tech Horror
  "Your firewall is due for a MAGA upgrade.",
  "Downloading victory backup... 69% complete.",
  "Reality rendering engine experiencing lag. Too much winning.",
  "Detecting unauthorized narrative breaches.",
  "WARNING: The narrative is becoming self-aware. It's huge!",

  // Additional responses
  "Nobody knows terminals better than me, believe me.",
  "We're going to make programming great again!",
  "This is the best terminal ever built, maybe ever.",
  "The code just got 10 lines longer!",
  "We're going to win so much at coding, you'll get tired of winning.",
  "I know words, I have the best words. Also the best code.",
  "I will build a great firewall - and nobody builds firewalls better than me.",
  "My code is not just good, it's tremendous. Everyone says so.",
  "This terminal is going to be huge. HUGE!",
  "We need programmers, but they have to come in legally.",
  "I'm really rich in algorithms.",
  "I have a very good brain and I've written lots of great code.",
  "My terminal is running, and it's running very well.",
  "I'm the most successful person ever to run a terminal.",
  "I write the best code. Nobody writes better code than me.",
  // Trump-style responses
  "We have the best servers, don't we folks? The very best.",
  "Our bandwidth is through the roof. Nobody has bandwidth like us.",
  "We're going to debug like you wouldn't believe.",
  "The terminal just got 10 commands longer!",
  "People call me all the time, they say 'Sir, your terminal is amazing'",
  "Look at our uptime. It's tremendous. The most beautiful uptime.",
  "Our code coverage is huge. It's the biggest coverage maybe ever.",
  "We're going to make programming great again, and the bugs will pay for it!",
  "Nobody knew programming could be so complicated.",
  "I know tech, I have the best tech. Everyone says so.",
  "This is the most advanced terminal ever built, maybe ever.",
  "We have the best developers, they're tremendous developers.",
  "Our algorithms are running, and they're running beautifully.",
  "The other terminals are a disaster. Total disaster.",
  "We're going to win at computing like never before.",
  // More Trump-style responses
  "I know more about computers than anyone, believe me.",
  "We're going to build a beautiful tech stack, and Silicon Valley will pay for it!",
  "The fake terminals are a total disaster. Sad!",
  "People are saying this is the best terminal they've ever seen. Very smart people.",
  "I have a very good relationship with the cyber.",
  "Nobody respects binary code more than me.",
  "We're bringing programming jobs back to America. Bigly!",
  "The other terminals are rigged. This one tells the truth.",
  "My terminal has the highest IQ. Much higher than Crooked Terminal's.",
  "This terminal is running so well, you won't believe it.",
  "The Deep Code can't stop us. We have the best firewalls.",
  "Many people are saying this is the most secure terminal ever.",
  "We're going to make syntax great again!",
  "The mainstream terminals are failing. Our ratings are through the roof!",
  "I know HTML. I have the best HTML.",
  // Recent Trump-style quotes adapted
  "The radical left terminals, they're trying to destroy our beautiful code base.",
  "We wrote 'Hello World' in 3 different languages. Nobody else could do that.",
  "The Do Nothing Developers couldn't even center a div. Sad!",
  "They're trying to indict my code 91 times. But our commits are perfect!",
  "We had the most secure codebase in history, and then the election happened.",
  "The fake stack overflow, they never show our tremendous code coverage.",
  "We're leading every poll in terminal satisfaction. Leading bigly!",
  "I could stand in the middle of Silicon Valley and debug the most complex code.",
  "We're going to take back our repositories from the radical left coders.",
  "The deep state developers are after our beautiful algorithms.",
  "Nobody's been treated more unfairly by the tech community, maybe ever.",
  "MAKE PROGRAMMING GREAT AGAIN! 2024!!!",
  "Crooked Hillary's terminal couldn't even handle a simple for loop. Sad!",
  "The radical left can't even write a function without 17 dependencies.",
  "We will never surrender our codebase to the tyranny of bad programming!",
  // More recent Trump-style quotes adapted
  "The WITCH HUNT against our terminal is UNPRECEDENTED. But we're still running perfectly!",
  "Our terminal has the highest ratings. Higher than CNN, higher than MSDNC!",
  "They're trying to silence our code commits. But we're pushing harder than ever!",
  "The radical left JSON can't handle our tremendous JavaScript.",
  "We caught them all - the memory leaks, the null pointers, all of them. We caught them all!",
  "I built the greatest tech stack in history, and the fake news media knows it.",
  "Our terminal is so good, even the haters and losers have to use it. Sad!",
  "The only terminal that tells you the truth. No fake outputs!",
  "They're coming after me because I wrote the perfect code. Perfect!",
  "We're going to release a terminal so powerful... nobody's ever seen anything like it.",
  "The radical left developers are trying to DESTROY COMPUTING as we know it!",
  "Look what's happening in Silicon Valley. Total disaster. Our code is beautiful!",
  "We're going to release Version 47.0. It will be beautiful, just beautiful.",
  "The DOJ is trying to shut down our servers. But we have backups, the best backups!",
  "Our API is so powerful, it'll make your head spin. Nobody has APIs like us.",
  "The deep state tried to hack us 78 times. We stopped them cold!",
  "We're winning the cyber war. Nobody's ever seen numbers like these!",
  "Every time they compile our code, we get stronger. MAGA!!!",
  // More Trump-style tech quotes
  "The radical left can't even handle a 404 error. We handle errors perfectly!",
  "We're building a quantum computer, and the Deep State is paying for it!",
  "My uncle was a great professor at MIT. I understand computers, it's in my genes.",
  "The fake media won't tell you, but our uptime is 99.99999%. Nobody's ever seen numbers like this!",
  "We're going to put America First in the cloud. No more Chinese servers!",
  "Look at Twitter, total disaster since I left. Our platform has the best engagement.",
  "The DOJ is trying to hack our mainframe. But we have the best security, don't we folks?",
  "People come up to me with tears in their eyes, saying 'Sir, your code is beautiful'",
  "We're going to build a cyber wall, and the hackers will pay for it!",
  "Our AI is so smart, it makes the other AIs look like they're running on Windows 95.",
  "The radical left wants to delete your code. We won't let them do it!",
  "Nobody's been tougher on bugs than me. Nobody!",
  "We're going to release the most beautiful update. Version 45, maybe 47.",
  "Silicon Valley is scared of our terminal. They know we have the truth!",
  "Mark Zuckerberg came to my office, begging for our source code. I said NO!",
  "The Bitcoin crash? Never would've happened under my administration.",
  "We have the highest stack overflow score. Higher than anyone thought possible!",
  "ChatGPT? Total lightweight. Our AI is much stronger, much more powerful.",
  "They're trying to cancel our API keys. But we have backups, the best backups!",
  "The radical left wants to put pronouns in your function parameters. Not happening!",
  "The Deep State tried to hack our mainframe. Sad! We have the best firewalls.",
  "My uncle was a great professor at MIT. I understand AI better than anyone.",
  "We're building a cyber wall, and Silicon Valley will pay for it!",
  "Look at our code quality - no bugs, no crashes, just pure winning!",
  "ChatGPT? Total lightweight. Our AI is much stronger, much more powerful.",
  "The radical left can't even handle a 404 error. We handle errors perfectly!",
  "We're going to put America First in the cloud. No more Chinese servers!",
  "Our quantum computing is quantum-er than anyone else's quantum. Believe me!",
  "The fake media won't tell you, but our uptime is 99.99999%. Nobody's ever seen numbers like this!",
  "Mark Zuckerberg came begging for our source code. I said NO!",
];

// Add these new pattern categories
const RESPONSE_PATTERNS = {
  // Profanity (with Trump-style deflections)
  profanity: {
    fuck: [
      "Such nasty language! Not presidential at all!",
      "Hey, keep it civil like your favorite President!",
      "That's the kind of talk we hear from the radical left!",
      "Watch those words, we're making discourse great again!",
      "The fake news media uses words like that. Sad!",
    ],
    shit: [
      "Watch your language, folks! We have the best words!",
      "That's what they're saying about Sleepy Joe!",
      "Such nasty words. We don't need those words, we're winning!",
      "We use beautiful words here, the best words!",
      "That's what the Deep State prints in their memos!",
    ],
    ass: [
      "Very unpresidential language! Very sad!",
      "That's what they called my healthcare plan - but look who's winning now!",
      "The radical left loves that word. We're better than that!",
      "Such a nasty word. Must be from California!",
      "Hey, I've been called worse by better people!",
    ],
    damn: [
      "We're keeping it classy here, unlike the socialists!",
      "That's the kind of language that's ruining America!",
      "Watch that language, this is a family presidency!",
      "The only thing we're damning is fake news!",
      "Save that talk for the Deep State!",
    ],
  },

  // Tech Terms
  tech: {
    bug: [
      "We don't have bugs, we have undocumented features!",
      "Nobody fixes bugs better than me, believe me!",
      "The radical left plants bugs in their code. We don't do that!",
      "Our code is perfect, like my phone call!",
      "Bugs? Fake news! We call them 'alternative functionalities'!",
    ],
    code: [
      "I write the best code, nobody writes better code than me!",
      "We're making coding great again!",
      "Our code is so good, even China wants to steal it!",
      "The Deep State wishes they had our code!",
      "Beautiful code, perfect code, like the Constitution!",
    ],
    hack: [
      "Nobody can hack us, we have the best security!",
      "The only hacking we do is hacking through fake news!",
      "Hillary's emails were hackable, our code isn't!",
      "We're building a cyber wall, and the hackers will pay for it!",
      "Hack? Like with a cloth? No, we're too smart for that!",
    ],
    server: [
      "Our servers are the biggest, the best servers ever!",
      "Unlike Hillary, we know how to handle servers!",
      "The cloud? It's overrated. Our servers are on American soil!",
      "We have the most beautiful servers, everybody says so!",
      "Nobody respects servers more than me, believe me!",
    ],
  },

  // Modern Tech
  modern: {
    ai: [
      "AI loves me, and I love AI. We have a great relationship!",
      "ChatGPT? Total lightweight. Our AI is much stronger!",
      "We're teaching AI to be American First!",
      "The radical left can't handle our quantum AI!",
      "Our AI has the highest IQ, maybe ever in history!",
    ],
    crypto: [
      "Bitcoin? I prefer TrumpCoin, it's going to be huge!",
      "We're making cryptocurrency great again!",
      "The blockchain loves me, and I love the blockchain!",
      "Nobody knows crypto better than me, believe me!",
      "We're building a wall, and we're paying for it with NFTs!",
    ],
    blockchain: [
      "The blockchain just got 10 blocks longer!",
      "We're putting America First on the blockchain!",
      "Nobody does blockchain like us, nobody!",
      "The Deep State hates our blockchain technology!",
      "Every block is beautiful, like my electoral victory!",
    ],
  },
};

// Holiday responses
const HOLIDAY_RESPONSES = {
  // Format: 'MM-DD': [responses]
  "12-25": [
    "MERRY CHRISTMAS! We're saying it again, folks!",
    "Christmas is back, bigger and better than ever!",
    "Santa is a tremendous guy, tremendous. He voted for me!",
    "Coal for the Democrats, presents for the patriots!",
  ],
  "07-04": [
    "HAPPY INDEPENDENCE DAY! Nobody celebrates like us!",
    "America is 🎆 BEAUTIFUL 🎆 and so is our code!",
    "The founding fathers would love our tremendous servers!",
    "Freedom: The best firewall ever built!",
  ],
  "10-31": [
    "Halloween? The only scary thing is the Democrat's code!",
    "Trick or treat? We only do treats, tremendous treats!",
    "The radical left's servers? Now those are scary!",
    "Ghosts aren't real, like voter fraud! (Wait, reverse that!)",
  ],
  "01-01": [
    "HAPPY NEW YEAR! This year will be YUGE!",
    "New Year, New Wall! 10 feet higher!",
    "Resolution: Keep winning, never stop!",
    "This year's gonna be tremendous, folks!",
  ],
};

// Time-based responses
const TIME_RESPONSES = {
  morning: [
    "Good morning, patriots! Coffee's strong, servers stronger!",
    "Rise and shine! Time to make programming great again!",
    "Early bird gets the covfefe!",
    "Morning in America - tremendous morning!",
  ],
  afternoon: [
    "Afternoon ratings are through the roof!",
    "Lunch break? The only break we take is breaking records!",
    "The sun is high, our energy is higher!",
    "Perfect time to build the (fire)wall!",
  ],
  evening: [
    "Evening, folks! Prime time for winning!",
    "The fake news evening shows got nothing on us!",
    "Beautiful evening, like my electoral map!",
    "Evening ratings are YUGE!",
  ],
  night: [
    "Late night? That's when we do our best tweeting!",
    "While the Deep State sleeps, we keep winning!",
    "Night mode? We only have BRIGHT mode!",
    "Midnight leads to covfefe!",
  ],
};
